version: '3'
services:
    mydb:
        image: "postgres"
        networks:
            - airflow-available-net
        environment: 
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"
        volumes:
            - ${FLATS_SCRAPER_DB_LOCATION}:/var/lib/postgresql/data
        ports:
            - "5433:5433"

    airflow-backend:
        image: postgres
        networks:
            - airflow-backend-net
        volumes:
            - ${AIRFLOW_DB_LOCATION}:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: "${AIRFLOW_DB_USER}"
            POSTGRES_PASSWORD: "${AIRFLOW_DB_PASSWORD}"
            POSTGRES_DB: "${AIRFLOW_DB_DATABASE}"
    airflow:
        build: ./airflow-engine
        # restart: always
        depends_on: 
            - airflow-backend
        networks:
            - airflow-backend-net
            - airflow-available-net
        environment: 
            AIRFLOW_DB_USER: "${AIRFLOW_DB_USER}"
            AIRFLOW_DB_PASSWORD: "${AIRFLOW_DB_PASSWORD}"
            AIRFLOW_DB_DATABASE: "${AIRFLOW_DB_DATABASE}"
            AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgres://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-backend/${AIRFLOW_DB_DATABASE}"
        volumes:
            - ./dags:/root/airflow/dags
        ports:
            - "8080:8080"


networks:
    airflow-backend-net:
    airflow-available-net: